branches:
  only:
  - master
  - develop
language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.10"
    - PRETTYNAME="BD65496MUV Arduino Library"
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/teamonestone/travis-ci-arduino/master/install.sh)
install:
script:
  - build_platform uno
  - build_platform mega2560
  - build_platform esp8266
  - build_platform m4
  - build_platform zero
  - build_platform leonardo
after_success:
  - source <(curl -SLs https://raw.githubusercontent.com/teamonestone/travis-ci-arduino/master/doxy_gen_and_deploy.sh)